### ISSUE TITLE
"進捗どうですか？" by Unityちゃん should be added.

### ISSUE THREAD

**Issue by teramonagi** [dichika/yeah#2]
Hi guys;

I hope that you are really enjoying the last day of this year.
I realized that there is a good voice source of "進捗どうですか？" in Japanese provided by Unityちゃん when I was reading the following article.
- http://zecl.hatenablog.com/entry/UniFSharp

I tried to download these resources and implemented it in year package.
But, I could not find it(wav or mp3 file) :(

I hope that you will try to implement it and the voice "進捗どうですか？" will allow us to acheive results in the near future.

Best regards;

**Comment by dichika** [comment]
Thanks!!! I added the unity-chan voices. Try "yeah::sinchoku(1)" !!!

**Comment by teramonagi** [comment]
It works in my environment too(Win)! Thanks alot

**Comment by dichika** [comment]
:+1:
